version: "4.17"
services:
  php-apache:
    ports:
      - "80:80"
    build: "./build/php"
    volumes:
      - ./app:/var/www/html
  mysql:
    ports:
      - "3306:3306"
    build: "./build/mysql"
    environment:
      MYSQL_ROOT_PASSWORD: "pass"
      MYSQL_DATABASE: "workforce-register"
    volumes:
      - dbData:/var/lib/mysql
volumes:
  app:
  dbData:
